replicaCount: 2

image:
  repository: 950274644703.dkr.ecr.ap-northeast-2.amazonaws.com/product/dev
  tag: '295c0e62d415fdc23800bc3466c98e99c51a5ca2'
  pullPolicy: IfNotPresent

service:
  name: dev-app
  targetPort: 8080

ingress:
  name: dev-ingress

loadbalancer:
  name: dev-alb

rollout:
  enabled: false
