replicaCount: 2

image:
  repository: 950274644703.dkr.ecr.ap-northeast-2.amazonaws.com/product/dev
  tag: '5ba987bb84ff9b2e6f369dc78c9bb4389752c750'
  pullPolicy: IfNotPresent

service:
  name: dev-app
  targetPort: 8080

ingress:
  name: dev-ingress

loadbalancer:
  name: dev-alb

rollout:
  enabled: false
