replicaCount: 2

image:
  repository: 950274644703.dkr.ecr.ap-northeast-2.amazonaws.com/product/dev
  tag: 'b7886d3f2e0912a34c6abe8646b896f64b078269'
  pullPolicy: IfNotPresent

service:
  name: dev-app
  targetPort: 8080

ingress:
  name: dev-ingress

loadbalancer:
  name: dev-alb

rollout:
  enabled: false
