replicaCount: 2

image:
  repository: 950274644703.dkr.ecr.ap-northeast-2.amazonaws.com/product/dev
  tag: '496e3730c8e90125795c084dc8c7fa824f2a3807'
  pullPolicy: IfNotPresent

service:
  name: dev-app
  targetPort: 8080

ingress:
  name: dev-ingress

loadbalancer:
  name: dev-alb

rollout:
  enabled: false
