replicaCount: 2

image:
  repository: 950274644703.dkr.ecr.ap-northeast-2.amazonaws.com/product/prod
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: prod-app
  targetPort: 8080

ingress:
  name: prod-ingress
