  apiVersion: actions.summerwind.dev/v1alpha1
  kind: RunnerDeployment
  metadata:
    name: dev-runner
    namespace: app
  spec:
    replicas: 2
    template:
      spec:
        repository: "dml113/day2-product"
        # 개발/운영으로 github action runner를 구분할때 아래 labels 활용
        labels:
        - dev
