name: Dev CI/CD Pipeline
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux, x64, dev]
    permissions:
      contents: write
      id-token: write  # for OIDC
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup QEMU and Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-role
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push multi-arch image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/product/dev
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag $IMAGE_URI:${{ github.sha }} \
            --push .

      - name: Update dev.values.yaml
        run: |
          sed -i "s|tag: .*|tag: '${GITHUB_SHA}'|" values/dev.values.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add values/dev.values.yaml
          git commit -m "chore: bump dev image tag to ${GITHUB_SHA}"
          git push origin dev

      - name: Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git push origin dev

      - name: ArgoCD Sync Dev App
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        run: |
          argocd login $ARGOCD_SERVER --username admin --password Skill53## --insecure
          argocd app sync dec
