name: Dev CI/CD Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  auto-merge-feature:
    if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'feature/')
    runs-on: [self-hosted, linux, x64, dev]
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Merge feature/* PR into dev
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-deploy:
    if: github.event_name == 'push'
    runs-on: [self-hosted, linux, x64, dev]
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU and Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-role
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push multi-arch image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/product/dev
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag $IMAGE_URI:${{ github.sha }} \
            --push .

      - name: Update dev.values.yaml
        run: |
          sed -i "s|tag: .*|tag: '${GITHUB_SHA}'|" values/dev.values.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add values/dev.values.yaml
          git commit -m "chore: bump dev image tag to ${GITHUB_SHA}"
          git pull --rebase origin dev || true
          git push origin dev

      - name: ArgoCD Sync Dev App
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64
          echo y | argocd login $ARGOCD_SERVER --username admin --password Skill53## --insecure
          argocd app sync dev
